---
title: "Homework 6"
author: "Zeqi Li"
date: "2024-12-02"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
```

# Problem 1
## Import weather data
```{r p1_data, message = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") |> 
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |> 
  select(name, id, everything())
```

## Perform bootstrapping
```{r p1_bootstrap}
bootstrap = function(df) {
  sample_frac(df, replace = TRUE) 
}

boot_samp = tibble(n = 1:5000) |> 
  mutate(strap_samp = map(n, \(i) bootstrap(df = weather_df)))
```

## Build a simple linear regression model
```{r p1_slr}
boot_slr = boot_samp |> 
  mutate(models = map(strap_samp, \(df) lm(tmax ~ tmin, data = df))) |> 
  select(-strap_samp)
```

## Extract $r^2$ and $log(\hat{\beta_{0}} * \hat{\beta_{1}})$ estimates
```{r p1_estimates}
boot_res = boot_slr |> 
  mutate(tidy_res = map(models, broom::tidy),
         glance_res = map(models, broom::glance)) |> 
  select(-models) |> 
  unnest(cols = c(tidy_res, glance_res),
         names_sep = "_")

est_df = boot_res |> 
  select(n, 
         tidy_res_term,
         tidy_res_estimate,
         glance_res_r.squared) |> 
  group_by(tidy_res_term) |> 
  pivot_wider(names_from = tidy_res_term,
              values_from = tidy_res_estimate) |> 
  rename(r_sq = glance_res_r.squared,
         beta_0 = `(Intercept)`,
         beta_1 = tmin) |> 
  mutate(log_betas = log(beta_0 * beta_1)) |> 
  select(-beta_0, -beta_1)
```

## Compute confidence intervals using all bootstrap samples
```{r p1_ci, warning = FALSE}
ci_df = est_df |> 
  summarize(r_sq_lb = quantile(r_sq, 0.025),
            r_sq_ub = quantile(r_sq, 0.975),
            log_betas_lb = quantile(log_betas, 0.025),
            log_betas_ub = quantile(log_betas, 0.975))
```

## Plot estimates with confidence intervals
### Histogram for $r^2$
```{r p1_plot1, message = FALSE}
est_df |> 
  ggplot(aes(x = r_sq)) +
  geom_histogram(binwidth = 0.005) +
  geom_vline(aes(xintercept = ci_df$r_sq_lb), 
             color = "blue", 
             linetype = "dashed") +
  geom_vline(aes(xintercept = ci_df$r_sq_ub), 
             color = "blue", 
             linetype = "dashed") +
  labs(title = expression(r^2 ~ " estimate distribution"),
       x = expression(r^2),
       y = "Frequency")
```

COMMENT

### Histogram for $log(\hat{\beta_{0}} * \hat{\beta_{1}})$
```{r p1_plot2, message = FALSE}
est_df |> 
  ggplot(aes(x = log_betas)) +
  geom_histogram(binwidth = 0.005) +
  geom_vline(aes(xintercept = ci_df$log_betas_lb), 
             color = "blue", 
             linetype = "dashed") +
  geom_vline(aes(xintercept = ci_df$log_betas_ub), 
             color = "blue", 
             linetype = "dashed") +
  labs(title = expression(log(beta[0] * beta[1]) ~ " estimate distribution"),
       x = expression(log(beta[0] * beta[1])),
       y = "Frequency")
```

COMMENT

# Problem 2

